# Generated by Django 4.2.3 on 2023-07-30 12:02

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('colour', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Drain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('drain', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='configfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('configfile', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reinforce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reinforce', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('slope', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('weigth', models.PositiveIntegerField(default=1)),
                ('heigth', models.PositiveIntegerField(default=1)),
                ('ventilation', models.BooleanField()),
                ('configfile_colour', models.BooleanField()),
                ('window', models.PositiveIntegerField(default=1)),
                ('open_window', models.PositiveIntegerField(default=1)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('colour', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.colour')),
                ('drain', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.drain')),
                ('configfile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.configfile')),
                ('reinforce', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.reinforce')),
                ('slope', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.slope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
