# Generated by Django 4.2.3 on 2023-08-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_window_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.colour'),
        ),
        migrations.AlterField(
            model_name='window',
            name='drain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.drain'),
        ),
        migrations.AlterField(
            model_name='window',
            name='configfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.configfile'),
        ),
        migrations.AlterField(
            model_name='window',
            name='reinforce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.reinforce'),
        ),
        migrations.AlterField(
            model_name='window',
            name='slope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.slope'),
        ),
    ]
