# Generated by Django 4.2.3 on 2023-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_window_colour_alter_window_drain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='window',
            options={'verbose_name': 'Window', 'verbose_name_plural': 'Windows'},
        ),
    ]
