# Generated by Django 4.2.3 on 2023-08-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_window_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('profile', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='window',
            old_name='heigth',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='window',
            old_name='configfile_colour',
            new_name='profile_colour',
        ),
        migrations.RenameField(
            model_name='window',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='window',
            name='configfile',
        ),
        migrations.DeleteModel(
            name='configfile',
        ),
        migrations.AddField(
            model_name='window',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.profile'),
        ),
    ]
