# Generated by Django 4.2.3 on 2023-08-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
