# Generated by Django 4.2.3 on 2023-08-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_subscription_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_expiration',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
