# Generated by Django 4.2.3 on 2023-08-16 19:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_phone_remove_user_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region='KG', unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.phone'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
