# Generated by Django 4.2.3 on 2023-08-17 15:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_phone_phone_user_alter_phone_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumbers',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
