# Generated by Django 4.2.3 on 2023-08-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_phonenumbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenumbers',
        ),
    ]
