# Generated by Django 4.2.3 on 2023-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_walletreduction_walletfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True, unique=True)),
                ('price', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
