# Generated by Django 4.2.3 on 2023-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='time',
            field=models.CharField(choices=[('month', 'month'), ('year', 'year')], max_length=100, null=True),
        ),
    ]
