# Generated by Django 4.2.3 on 2023-09-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.subscriptions'),
        ),
    ]
